### ISSUE TITLE
Error for code?

### ISSUE THREAD

**Issue by Mystic4l** [HKUDS/GPT-ST#4]
Whether there is no indentation in line 21 of the time_add method of load_dataset
![屏幕截图 2024-04-25 213152](https://github.com/HKUDS/GPT-ST/assets/127591572/e6c13ea7-1388-4e6f-9198-76f10d77e865)

**Comment by Mystic4l** [comment]
if indentation of day_init = day_init + 1 is right。Why is the result of day_init >6 holiday_init = 2 and not week_init>6？

**Comment by LZH-YS1998** [comment]
Hello, thank you for your interest in our work. Here, 'day_init' represents time in day, and 'week_init' represents day in week, so the 'day_init' in line 21 does not need indentation. Since we do not use the 'holiday' element in our model, we overlooked this issue. When 'day_init' < 6, 'holiday_init' = 1, here 'day_init' should be corrected to 'week_init'. Thank you for pointing out this issue.
